# Generated by Django 3.0.8 on 2020-08-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Com_Contents',
            new_name='com_Contents',
        ),
    ]
